# Setup
title:        Coding Weasel
tagline:      .NET-everything and IT-anything
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Mihai Pirvu
  url:        https://uizzuw.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown